
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sys.utd.Presentacion;

import com.sys.utd.ConexionBD.ConexionBD;
import com.sys.utd.Daos.Dao_OC_Det;
import com.sys.utd.Entidades.Entidad_OC_Det;
import com.sys.utd.Entidades.ItemCentroCostos;
import com.sys.utd.Reportes.ReporteOC;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jonathan
 */
public class JIFOC_Mod extends javax.swing.JInternalFrame {

   private ConexionBD conexion;
   private DefaultTableModel modelo;
   private Entidad_OC_Det det;
   private Dao_OC_Det daoDet;
   private int iditemccostos;
   private int id_oc;
   private int iddetreq;
   private float item;
   private int idreq;
   private float cant;
   private ReporteOC reporte;
   private int id_ccostos=0;
   private TableRowSorter trsFiltro;
   
   
   private DefaultTableModel modeloLista;
   
   private int idus=MDIPrincipal.getvSeccion();
    public JIFOC_Mod() {
        initComponents();
        
        conexion=new ConexionBD();
        
        
            Color c1=new Color(66,111,166);
            Color c2=new Color(102,174,118);
            JPColor miColor=new JPColor(c1,c2);
            miColor.setSize(this.getSize());
            panel_enc.add(miColor);
        
        
        modelo=new DefaultTableModel();
        modeloLista=new DefaultTableModel();
  
    try
    {
        
        
        
        ResultSet obj=conexion.executeQuery("SELECT nombre_centro_costos FROM utdvvcc.centrocostos WHERE estado=true ORDER BY nombre_centro_costos ASC");//Consulta para traer el nombre de centro de costos
        
        while(obj.next())
        {
            cb_ccostos.addItem(obj.getObject("nombre_centro_costos"));//Llena JCombobox con el nombre del centro de costos
        }
   
   
       //Consulta para traer el ultimo registro de y sumarle 1 para el consecutivo orden compra
      
       ResultSet obj1=conexion.executeQuery("SELECT iva_descripcion FROM tipos_iva ORDER BY iva_descripcion ASC");

       while(obj1.next())
       {
           cb_iva.addItem(obj1.getObject("iva_descripcion"));//Llana el JCombobox con el nombre de la unida de medida
       }
       
       
      
 
        conexion.desconectar();
        
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
        //modelo de tabla
        modelo.addColumn("ID");
        modelo.addColumn("ID Det Req");
        modelo.addColumn("Referencia");
        modelo.addColumn("Descripción");
        modelo.addColumn("UM");
        modelo.addColumn("Cant.");       
        modelo.addColumn("VR Unitario");
        modelo.addColumn("Desc.");
        modelo.addColumn("IVA");
        modelo.addColumn("Total");
        
        
        modeloLista.addColumn("ID");
        modeloLista.addColumn("ID detalle");
        modeloLista.addColumn("IT");
        modeloLista.addColumn("Referencia");
        modeloLista.addColumn("Descripción");
        modeloLista.addColumn("UM");
        modeloLista.addColumn("Cantidad");
        
        panel_linea.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Detalle_Orden = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_refe = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_cant = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_vlor_unit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cb_iva = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txt_dto_com = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_can = new javax.swing.JButton();
        txt_um = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_catalogo = new javax.swing.JButton();
        JD_Pedidos = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        btn_sel = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_insumos = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        txt_filtro = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cb_filtro = new javax.swing.JComboBox();
        panel_enc = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_orden = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area_obs = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_area_con = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_buscarOC = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb_ccostos = new javax.swing.JComboBox();
        cb_item = new javax.swing.JComboBox();
        cb_proveedor = new javax.swing.JComboBox();
        txt_proveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        panel_linea = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tb_detalle = new javax.swing.JTable();
        btn_adicionar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lb_iva = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lb_dcto = new javax.swing.JLabel();
        lb_total = new javax.swing.JLabel();
        btn_terminar = new javax.swing.JButton();

        JD_Detalle_Orden.setTitle("Linea Orden de Compra");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel8.setText("Descripción *");

        txt_descripcion.setEditable(false);

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel9.setText("Referencia *");

        txt_refe.setEditable(false);

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel10.setText("Cantidad *");

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel11.setText("Vlor.Unitario:$ *");

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel12.setText("U.M*");

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel13.setText("IVA: % *");

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel14.setText("Dto.Comercial:(%)*");

        txt_dto_com.setText("0");

        btn_aceptar.setText("Aceptar");
        btn_aceptar.setToolTipText("");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_can.setText("Cancelar");
        btn_can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_canActionPerformed(evt);
            }
        });

        txt_um.setEditable(false);
        txt_um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_umActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Campos Obligatorios *");

        btn_catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/catalogo.png"))); // NOI18N
        btn_catalogo.setToolTipText("Pedidos Pendientes");
        btn_catalogo.setBorderPainted(false);
        btn_catalogo.setContentAreaFilled(false);
        btn_catalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_catalogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_refe, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_um, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_cant, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_vlor_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_aceptar)
                            .addGap(7, 7, 7)
                            .addComponent(btn_can)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_dto_com, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_refe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(txt_vlor_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(cb_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(txt_um, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_dto_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_aceptar)
                            .addComponent(btn_can))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout JD_Detalle_OrdenLayout = new javax.swing.GroupLayout(JD_Detalle_Orden.getContentPane());
        JD_Detalle_Orden.getContentPane().setLayout(JD_Detalle_OrdenLayout);
        JD_Detalle_OrdenLayout.setHorizontalGroup(
            JD_Detalle_OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_Detalle_OrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JD_Detalle_OrdenLayout.setVerticalGroup(
            JD_Detalle_OrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_Detalle_OrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JD_Pedidos.setTitle("Buscar Insumo");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Insumos"));

        btn_sel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/sel.png"))); // NOI18N
        btn_sel.setToolTipText("Seleccionar Fila");
        btn_sel.setBorderPainted(false);
        btn_sel.setContentAreaFilled(false);
        btn_sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selActionPerformed(evt);
            }
        });

        tb_insumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tb_insumos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btn_sel)
                .addGap(0, 337, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar"));

        txt_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_filtroKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Buscar Por");

        cb_filtro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Referencia", "Descripción" }));
        cb_filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_filtroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(cb_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cb_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout JD_PedidosLayout = new javax.swing.GroupLayout(JD_Pedidos.getContentPane());
        JD_Pedidos.getContentPane().setLayout(JD_PedidosLayout);
        JD_PedidosLayout.setHorizontalGroup(
            JD_PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JD_PedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JD_PedidosLayout.setVerticalGroup(
            JD_PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_PedidosLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Modificar Ordenes de Compra --UTDVVCC--");

        jLabel34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 0, 0));
        jLabel34.setText("ORDENES DE COMPRA");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/oc.png"))); // NOI18N

        javax.swing.GroupLayout panel_encLayout = new javax.swing.GroupLayout(panel_enc);
        panel_enc.setLayout(panel_encLayout);
        panel_encLayout.setHorizontalGroup(
            panel_encLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_encLayout.createSequentialGroup()
                .addGap(487, 487, 487)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_encLayout.setVerticalGroup(
            panel_encLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_encLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
            .addGroup(panel_encLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Orden de Compra"));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Orden de Compra N° *");

        txt_orden.setBackground(new java.awt.Color(255, 255, 102));
        txt_orden.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_orden.setText("?");
        txt_orden.setToolTipText("");

        txt_area_obs.setColumns(20);
        txt_area_obs.setRows(5);
        jScrollPane1.setViewportView(txt_area_obs);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Observación:");

        txt_area_con.setColumns(20);
        txt_area_con.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        txt_area_con.setRows(5);
        txt_area_con.setText("Favor facturar a nombre FIDEICOMISOS FID. 3-4-405 MALLA VIAL,\nNIT 830.054.076-2, *fecha*\nTiempo de entrega: Inmediato .\nForma de pago: Crédito 30 días\nSitio de entrega: Km 14 Recta Cali - Palmira, entrada al CIAT.\n");
        jScrollPane3.setViewportView(txt_area_con);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Condiciones: *");

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Campos Obligatorios *");

        btn_buscarOC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/buscar.png"))); // NOI18N
        btn_buscarOC.setBorderPainted(false);
        btn_buscarOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarOCActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Centro Costos: *");

        cb_ccostos.setEditable(true);
        cb_ccostos.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_ccostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ccostosActionPerformed(evt);
            }
        });

        cb_item.setEditable(true);
        cb_item.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_itemActionPerformed(evt);
            }
        });

        cb_proveedor.setEditable(true);
        cb_proveedor.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_proveedorActionPerformed(evt);
            }
        });

        txt_proveedor.setToolTipText("Ej: Inicial_Prove + SHIFT");
        txt_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_proveedorActionPerformed(evt);
            }
        });
        txt_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_proveedorKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Proveedor: *");

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_ccostos, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_item, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_buscarOC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5))
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txt_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_actualizar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(cb_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19))
                        .addComponent(btn_buscarOC, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(cb_ccostos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txt_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btn_actualizar))
                .addContainerGap())
        );

        panel_linea.setBorder(javax.swing.BorderFactory.createTitledBorder("Linea de Orden de Compra"));

        tb_detalle.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        tb_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(tb_detalle);

        btn_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/add.png"))); // NOI18N
        btn_adicionar.setToolTipText("Adicionar");
        btn_adicionar.setBorderPainted(false);
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarbtn_adicionarActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/delete.png"))); // NOI18N
        btn_eliminar.setToolTipText("Eliminar");
        btn_eliminar.setBorderPainted(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarbtn_eliminarActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel29.setText("TOTAL:$");

        jLabel30.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel30.setText("Dto. Com.:$");

        lb_iva.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lb_iva.setText("0,0");

        jLabel38.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel38.setText(".I.V.A:$");

        lb_dcto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lb_dcto.setText("0,0");

        lb_total.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lb_total.setText("0,0");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_dcto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29)
                                .addComponent(lb_total))
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_iva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel38))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(lb_dcto))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_lineaLayout = new javax.swing.GroupLayout(panel_linea);
        panel_linea.setLayout(panel_lineaLayout);
        panel_lineaLayout.setHorizontalGroup(
            panel_lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lineaLayout.createSequentialGroup()
                .addComponent(jScrollPane7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_lineaLayout.setVerticalGroup(
            panel_lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lineaLayout.createSequentialGroup()
                .addGroup(panel_lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_lineaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_adicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_terminar.setText("Terminar");
        btn_terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_enc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_linea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_terminar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_enc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_linea, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_terminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adicionarbtn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarbtn_adicionarActionPerformed
        JD_Detalle_Orden.pack();
        JD_Detalle_Orden.setLocationRelativeTo(null);
        JD_Detalle_Orden.setVisible(true);
        JD_Detalle_Orden.setResizable(false);
    }//GEN-LAST:event_btn_adicionarbtn_adicionarActionPerformed

    private void btn_eliminarbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarbtn_eliminarActionPerformed
         int opc=JOptionPane.showConfirmDialog(null,"Desea eliminar una Linea?", "Aviso!", JOptionPane.YES_NO_OPTION); 
          
        if(opc==JOptionPane.YES_OPTION)
        {
             eliminarRegistroTabla();

        }
          
    }//GEN-LAST:event_btn_eliminarbtn_eliminarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        try
        {
            
            det=new Entidad_OC_Det();
            daoDet=new Dao_OC_Det();
            int subtotal,total_linea, idiva;
            float vlordescuento, cantidad, descuento, vloriva,vlorunitario;
            int can_par_req = 0;
           
            
      
            
            if(txt_dto_com.getText().matches("[0-9]*"))
            {
            
            
            vlorunitario=(Float.parseFloat(txt_vlor_unit.getText()));
            cantidad=Float.parseFloat(txt_cant.getText());
            descuento=Float.parseFloat(txt_dto_com.getText());
            
            
            
            det.setId_det_req(iddetreq);
            det.setVlorunitario(vlorunitario);
            
            if(cantidad > cant)
            {
                JOptionPane.showMessageDialog(null, "La cantidad no puede ser mayor que el Pedido solicitado");
            }else
            {
                det.setCantidad(Float.parseFloat(txt_cant.getText()));
                
                
                if(cb_iva.getSelectedItem().equals("%0"))
                {
                    
                    
                    vlordescuento=((vlorunitario * cantidad)*(descuento/100));
                    subtotal=(int) ((vlorunitario*cantidad)- vlordescuento);
                    vloriva=0;
                    total_linea=subtotal;
                    idiva=1;
                    
                    det.setVloriva(vloriva);
                    det.setIdiva(idiva);
                    det.setTotal(total_linea);
                    det.setIdoc(id_oc);
                    det.setObse("REQ " + idreq + " ITEM " + item);
                    det.setVlordescuento(vlordescuento);
                    det.setDescuento(String.valueOf(descuento));
                    det.setCantparcial(cantidad);
                    
                    daoDet.guardar(det);
                    limpiarCampos();
                    LimpiarTabla();
                    detalleTabla();
                    sumaCampos();
                    
                    conexion.executeUpdateQuery("UPDATE listadopedidos.detalle_pedido SET cantidad_parcial=cantidad_parcial-"+cantidad+" WHERE id_dt="+iddetreq+"");

                    ResultSet obj=conexion.executeQuery("SELECT cantidad_parcial FROM listadopedidos.detalle_pedido WHERE id_dt="+iddetreq+"");
                
                    while (obj.next())
                    {
                        can_par_req=obj.getInt("cantidad_parcial");
                    }
                
                    if(can_par_req==0)
                    {
                        conexion.executeUpdateQuery("UPDATE listadopedidos.detalle_pedido SET id_estado=3 WHERE id_dt="+iddetreq+"");
                    }
                    conexion.desconectar();
                }
                 if(cb_iva.getSelectedItem().equals("%5"))
                {
                    
                    
                    vlordescuento=((vlorunitario * cantidad)*(descuento/100));
                    subtotal=(int) ((vlorunitario*cantidad)- vlordescuento);
                    vloriva=(float) (subtotal * 0.05);
                    total_linea=(int) (subtotal+vloriva);
                    idiva=4;
                    
                    det.setVloriva(vloriva);
                    det.setIdiva(idiva);
                    det.setTotal(total_linea);
                    det.setIdoc(id_oc);
                    det.setObse("REQ: " + idreq + " ITEM " + item);
                    det.setVlordescuento(vlordescuento);
                    det.setDescuento(String.valueOf(descuento));
                    det.setCantparcial(cantidad);
                    
                    daoDet.guardar(det);
                    limpiarCampos();
                    LimpiarTabla();
                    detalleTabla();
                    sumaCampos();
                    
                     conexion.executeUpdateQuery("UPDATE listadopedidos.detalle_pedido SET cantidad_parcial=cantidad_parcial-"+cantidad+" WHERE id_dt="+iddetreq+"");

                     
                     ResultSet obj=conexion.executeQuery("SELECT cantidad_parcial FROM listadopedidos.detalle_pedido WHERE id_dt="+iddetreq+"");
                
                    while (obj.next())
                    {
                        can_par_req=obj.getInt("cantidad_parcial");
                    }
                
                    if(can_par_req==0)
                    {
                        conexion.executeUpdateQuery("UPDATE listadopedidos.detalle_pedido SET id_estado=3 WHERE id_dt="+iddetreq+"");
                    }
                    conexion.desconectar();
                    
                }
                 
                    if(cb_iva.getSelectedItem().equals("%16"))
                {
                    
                    
                    vlordescuento=((vlorunitario * cantidad)*(descuento/100));
                    subtotal=(int) ((vlorunitario*cantidad)- vlordescuento);
                    vloriva=(float) (subtotal * 0.16);
                    total_linea=(int) (subtotal+vloriva);
                    idiva=3;
                    
                    det.setVloriva(vloriva);
                    det.setIdiva(idiva);
                    det.setTotal(total_linea);
                    det.setIdoc(id_oc);
                    det.setObse("REQ: " + idreq + " ITEM " + item);
                    det.setVlordescuento(vlordescuento);
                    det.setDescuento(String.valueOf(descuento));
                    det.setCantparcial(cantidad);
                    
                    daoDet.guardar(det);
                    limpiarCampos();
                    LimpiarTabla();
                    detalleTabla();
                    sumaCampos();
                    
                    conexion.executeUpdateQuery("UPDATE listadopedidos.detalle_pedido SET cantidad_parcial=cantidad_parcial-"+cantidad+" WHERE id_dt="+iddetreq+"");

                    ResultSet obj=conexion.executeQuery("SELECT cantidad_parcial FROM listadopedidos.detalle_pedido WHERE id_dt="+iddetreq+"");
                
                    while (obj.next())
                    {
                        can_par_req=obj.getInt("cantidad_parcial");
                    }
                
                    if(can_par_req==0)
                    {
                        conexion.executeUpdateQuery("UPDATE listadopedidos.detalle_pedido SET id_estado=3 WHERE id_dt="+iddetreq+"");
                    }
                    conexion.desconectar();
                    
                }
                    
                       if(cb_iva.getSelectedItem().equals("%19"))
                {
                    
                    
                    vlordescuento=((vlorunitario * cantidad)*(descuento/100));
                    subtotal=(int) ((vlorunitario*cantidad)- vlordescuento);
                    vloriva=(float) (subtotal * 0.19);
                    total_linea=(int) (subtotal+vloriva);
                    idiva=5;
                    
                    det.setVloriva(vloriva);
                    det.setIdiva(idiva);
                    det.setTotal(total_linea);
                    det.setIdoc(id_oc);
                    det.setObse("REQ: " + idreq + " ITEM " + item);
                    det.setVlordescuento(vlordescuento);
                    det.setDescuento(String.valueOf(descuento));
                    det.setCantparcial(cantidad);
                    
                    daoDet.guardar(det);
                    limpiarCampos();
                    LimpiarTabla();
                    detalleTabla();
                    sumaCampos();
                    
                    conexion.executeUpdateQuery("UPDATE listadopedidos.detalle_pedido SET cantidad_parcial=cantidad_parcial-"+cantidad+" WHERE id_dt="+iddetreq+"");

                    ResultSet obj=conexion.executeQuery("SELECT cantidad_parcial FROM listadopedidos.detalle_pedido WHERE id_dt="+iddetreq+"");
                
                    while (obj.next())
                    {
                        can_par_req=obj.getInt("cantidad_parcial");
                    }
                
                    if(can_par_req==0)
                    {
                        conexion.executeUpdateQuery("UPDATE listadopedidos.detalle_pedido SET id_estado=3 WHERE id_dt="+iddetreq+"");
                    }
                    conexion.desconectar();
                    
                }
            }
          }else
            {
                JOptionPane.showMessageDialog(null, "Los campos cantidad,valor unitario y dcto. comercial son númericos", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_canActionPerformed
        JD_Detalle_Orden.dispose();
    }//GEN-LAST:event_btn_canActionPerformed

    private void txt_umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_umActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_umActionPerformed

    private void btn_catalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_catalogoActionPerformed
       try {
           JD_Pedidos.pack();
           JD_Pedidos.setVisible(true);
           JD_Pedidos.setResizable(false);
           
           System.out.println(iditemccostos);
           
           buscarInsumo(id_ccostos);
       } catch (SQLException ex) {
           Logger.getLogger(JIFOC_Mod.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btn_catalogoActionPerformed

    private void btn_selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selActionPerformed

        String ref,des,um;
        

        if(tb_insumos.isRowSelected(tb_insumos.getSelectedRow()))
        {
            
            idreq=(int) tb_insumos.getValueAt(tb_insumos.getSelectedRow(), 0);
            iddetreq=(int) tb_insumos.getValueAt(tb_insumos.getSelectedRow(), 1);
            item=(float) tb_insumos.getValueAt(tb_insumos.getSelectedRow(), 2);
            ref =(String) tb_insumos.getValueAt(tb_insumos.getSelectedRow(), 3);
            des=(String) tb_insumos.getValueAt(tb_insumos.getSelectedRow(), 4);
            um=(String) tb_insumos.getValueAt(tb_insumos.getSelectedRow(), 5);
            cant=(float) tb_insumos.getValueAt(tb_insumos.getSelectedRow(), 6);
            
            
            txt_refe.setText(ref);
            txt_descripcion.setText(des);
            txt_um.setText(um);
            txt_cant.setText(String.valueOf(cant));

          

            JD_Pedidos.dispose();

          

        }else
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla!", "Alerta!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_selActionPerformed

    private void btn_terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terminarActionPerformed
        reporte=new ReporteOC();
        
        reporte.ejecutarReporte(id_oc);
        
       
    }//GEN-LAST:event_btn_terminarActionPerformed

    private void btn_buscarOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarOCActionPerformed
          try
       {
        int id=Integer.parseInt(txt_orden.getText());
        ItemCentroCostos item= (ItemCentroCostos) cb_item.getSelectedItem();
        iditemccostos=item.getIditem();
        
           buscarOC(id, iditemccostos);
        
       }catch (NumberFormatException e)
       {
           JOptionPane.showMessageDialog(this, e);
       } catch (SQLException ex) {
            Logger.getLogger(JIFPedidos_Mod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_buscarOCActionPerformed

    private void cb_ccostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ccostosActionPerformed
        try
        {
            conexion=new ConexionBD();

            

            if(cb_ccostos.getSelectedItem()!=null)
            {
                String centro=cb_ccostos.getSelectedItem().toString();
                ResultSet obj=conexion.executeQuery("SELECT id_centrocostos FROM utdvvcc.centrocostos WHERE nombre_centro_costos='"+centro+"'");

                while(obj.next())
                {
                    id_ccostos=obj.getInt("id_centrocostos");
                }
                cb_item.removeAllItems();
            }
            cargarItem(id_ccostos);

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cb_ccostosActionPerformed

    private void cb_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_itemActionPerformed

    private void cb_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_proveedorActionPerformed
        if(cb_proveedor.getSelectedItem()!=null)
        {
            try {
                conexion=new ConexionBD();
                long nit;

                String nombre=cb_proveedor.getSelectedItem().toString();
                ResultSet obj=conexion.executeQuery("SELECT nit_proveedor FROM proveedores.proveedor WHERE prove_razon_social='"+nombre+"'");

                while(obj.next())
                {
                    nit=obj.getLong("nit_proveedor");
                    txt_proveedor.setText("");
                    txt_proveedor.setText(String.valueOf(nit));
                }
                conexion.desconectar();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cb_proveedorActionPerformed

    private void txt_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_proveedorActionPerformed

    private void txt_proveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_proveedorKeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_SHIFT)
        {
            try {
                cb_proveedor.removeAllItems();
                buscarProveedores();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txt_proveedorKeyReleased

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
      conexion.executeUpdateQuery("UPDATE ordenescompra.ordencomprautd SET id_proveedor="+txt_proveedor.getText()+", observaciones='"+txt_area_obs.getText()+"', condiciones='"+txt_area_con.getText()+"', fecha_mod='"+new Date()+"' WHERE id_oc="+id_oc+"");
      panel_linea.setVisible(true);
      detalleTabla();
      
      btn_actualizar.setEnabled(false);
      
      
      conexion.desconectar();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void txt_filtroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtroKeyTyped
        txt_filtro.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (txt_filtro.getText());
                txt_filtro.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tb_insumos.getModel());
        tb_insumos.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txt_filtroKeyTyped

    private void cb_filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_filtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_filtroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_Detalle_Orden;
    private javax.swing.JDialog JD_Pedidos;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_buscarOC;
    private javax.swing.JButton btn_can;
    private javax.swing.JButton btn_catalogo;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_sel;
    private javax.swing.JButton btn_terminar;
    private javax.swing.JComboBox cb_ccostos;
    private javax.swing.JComboBox cb_filtro;
    private javax.swing.JComboBox cb_filtro2;
    private javax.swing.JComboBox cb_filtro3;
    private javax.swing.JComboBox cb_item;
    private javax.swing.JComboBox cb_iva;
    private javax.swing.JComboBox cb_proveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lb_dcto;
    private javax.swing.JLabel lb_iva;
    private javax.swing.JLabel lb_total;
    private javax.swing.JPanel panel_enc;
    private javax.swing.JPanel panel_linea;
    private javax.swing.JTable tb_detalle;
    private javax.swing.JTable tb_insumos;
    private javax.swing.JTextArea txt_area_con;
    private javax.swing.JTextArea txt_area_obs;
    private javax.swing.JTextField txt_cant;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_dto_com;
    private javax.swing.JTextField txt_filtro;
    private javax.swing.JTextField txt_filtro2;
    private javax.swing.JTextField txt_filtro3;
    private javax.swing.JTextField txt_orden;
    private javax.swing.JTextField txt_proveedor;
    private javax.swing.JTextField txt_refe;
    private javax.swing.JTextField txt_um;
    private javax.swing.JTextField txt_vlor_unit;
    // End of variables declaration//GEN-END:variables

   public void detalleTabla()
   {
       try
        {
         conexion=new ConexionBD();
            
        ResultSet obj=conexion.executeQuery("SELECT d.id_det_oc,d.id_det_req, r.referencia, r.descripcion, r.um, d.cantidad, d.vlor_unitario, d.vlordescuento,d.vlor_iva, d.total FROM ordenescompra.det_oc_utd d  JOIN listadopedidos.detalle_pedido r ON d.id_det_req=r.id_dt JOIN ordenescompra.ordencomprautd o ON o.id_oc=d.id_oc WHERE  d.id_oc="+id_oc+" ");
            
         while (obj.next()) 
        {
        
        Object [] datos = new Object[10];
        
     
        for (int i=0;i<10;i++)
        {
            datos[i] =obj.getObject(i+1);
        }

         modelo.addRow(datos);
       
        }
         
           
           tb_detalle.setModel(modelo);
           
        TableColumnModel columnModel =tb_detalle.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(5);
        columnModel.getColumn(1).setPreferredWidth(5);
        columnModel.getColumn(2).setPreferredWidth(50);
        columnModel.getColumn(3).setPreferredWidth(70);
        columnModel.getColumn(4).setPreferredWidth(5);
        columnModel.getColumn(5).setPreferredWidth(10);
        columnModel.getColumn(6).setPreferredWidth(10);
        columnModel.getColumn(7).setPreferredWidth(10);
        columnModel.getColumn(8).setPreferredWidth(20);
        columnModel.getColumn(9).setPreferredWidth(20);
           
           
           setCellRender(tb_detalle);
           conexion.desconectar();
           sumaCampos();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
   }
   
     public void LimpiarTabla()
    {
  
        for(int i=modelo.getRowCount()-1;i>=0;i--)
        {
            modelo.removeRow(i);
            
        }
    }
     
       public void LimpiarTabla2()
    {
  
        for(int i=modeloLista.getRowCount()-1;i>=0;i--)
        {
            modeloLista.removeRow(i);
            
        }
    }
 
     public void limpiarCampos()
     {
         txt_um.setText("");
         txt_refe.setText("");
         txt_descripcion.setText("");
         txt_dto_com.setText("0");
         txt_vlor_unit.setText("0");
         txt_dto_com.setText("0");
     }
     
     
     public void buscarInsumo(int iditem) throws SQLException
    {
        conexion=new ConexionBD();
        LimpiarTabla2();
        ResultSet obj=conexion.executeQuery("SELECT p.id_pedido,d.id_dt,d.item,d.referencia,d.descripcion, d.um, d.cantidad_parcial FROM  listadopedidos.pedido p JOIN listadopedidos.detalle_pedido d ON p.id_pedido=d.id_pedido JOIN utdvvcc.itemccostos i ON i.id_item_ccostos=p.id_item_ccostos JOIN utdvvcc.centrocostos c ON c.id_centrocostos=i.id_centrocostos WHERE c.id_centrocostos="+id_ccostos+" AND d.id_estado=2 OR d.id_estado=1 ");
        
        
        while (obj.next()) 
        {
        
        Object [] datos = new Object[7];
        
     
        for (int i=0;i<7;i++)
        {
            datos[i] =obj.getObject(i+1);
        }

         modeloLista.addRow(datos);
       
        }
           tb_insumos.setModel(modeloLista);
           
        TableColumnModel columnModel =tb_insumos.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(10);
        columnModel.getColumn(2).setPreferredWidth(10);
        columnModel.getColumn(3).setPreferredWidth(70);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(10);
        columnModel.getColumn(6).setPreferredWidth(10);
        
           setCellRender(tb_insumos);
           conexion.desconectar();
    
    }
     
       public void setCellRender(JTable table) {
            Enumeration<TableColumn> en = table.getColumnModel().getColumns();
                    while (en.hasMoreElements()) {
                        TableColumn tc = en.nextElement();
                        tc.setCellRenderer(new CellRenderer());
        }
    }
       
       
       
       public void sumaCampos()
       {
           float vlordcto=0;
           float vlorIva=0;
           int total=0;
           
            DecimalFormatSymbols dfs = new DecimalFormatSymbols();
            dfs.setPerMill('.');
            java.text.DecimalFormat formato = new java.text.DecimalFormat("'Total: $' #,##0.00",dfs);

           
           
           for(int i=0; i<tb_detalle.getRowCount(); i++)
           {
               vlordcto+=(float) tb_detalle.getValueAt(i, 7);
               vlorIva+=(float) tb_detalle.getValueAt(i, 8);
               total+=(int) tb_detalle.getValueAt(i,9);
           }
           
           
          lb_dcto.setText(formato.format(vlordcto));
          lb_iva.setText(formato.format(vlorIva));
          lb_total.setText(formato.format(total));

       }
       
       
       
       public void eliminarRegistroTabla()
    {
         conexion=new ConexionBD();
         int id=Integer.parseInt(txt_orden.getText());
         String obse="Liberado de la OC " + id;
        
        //Verifica que la fila de la tabla esta seleccionada
        if(tb_detalle.isRowSelected(tb_detalle.getSelectedRow()))
        {
           int row = tb_detalle.getSelectedRow();

        for(int i = 0; i < modelo.getRowCount(); i++)
        {
           conexion.executeUpdateQuery("DELETE FROM ordenescompra.det_oc_utd WHERE id_det_oc="+modelo.getValueAt(row,0)+"");
           conexion.executeUpdateQuery("UPDATE listadopedidos.detalle_pedido SET cantidad_parcial=cantidad_parcial + "+modelo.getValueAt(row, 5)+", id_estado=1, observacion='"+obse+"' WHERE id_dt="+modelo.getValueAt(row, 1)+" ");

        }
         int numRows = tb_detalle.getSelectedRows().length;
         
         for(int i = 0; i < numRows ; i++ )
         {
            modelo.removeRow(row);
         } 
       
        }         
 
     else
     {
      JOptionPane.showMessageDialog(this, "Debe seleccionar un registro de la tabla para eliminarlo!."
         ,"Aviso", JOptionPane.WARNING_MESSAGE);
     }
         conexion.executeUpdateQuery("UPDATE ordenescompra.ordencomprautd SET observaciones='"+txt_area_obs.getText()+"' WHERE id_oc="+id_oc+"");

           conexion.desconectar(); 
          
          LimpiarTabla();
          detalleTabla();  
          sumaCampos();
    }
       
         public void buscarOC(int id, int idcentro) throws SQLException
     {
         
      try
      {
         conexion=new ConexionBD();
         
         String obse=null;
         String con=null;
         long nitproveedor=0;
         
         
         
         ResultSet obj=conexion.executeQuery("SELECT id_oc AS id,o.observaciones AS obse, o.condiciones AS con, o.id_proveedor AS idproveedor FROM ordenescompra.ordencomprautd o  WHERE o.con_ccostos="+id+" AND id_itemccostos="+idcentro+" AND o.id_usuario="+idus+"");
         
        if(obj.first())
       {
       
      
        obj.beforeFirst();
        while (obj.next())
        {
            obse=obj.getString("obse");
            con=obj.getString("con");
            id_oc=obj.getInt("id");
            nitproveedor=obj.getLong("idproveedor");
            
        }
        
        
        
        txt_area_obs.setText(obse);
        txt_area_con.setText("");
        txt_area_con.setText(con);
        txt_proveedor.setText(String.valueOf(nitproveedor));
        btn_buscarOC.setEnabled(false);
        txt_orden.setEditable(false);
       
        
       
        conexion.desconectar();
        
        
           
        }else
       {
         JOptionPane.showMessageDialog(null, "No se encuentra el ID "+ id+" de la OC ó  no esta autorizado para la modificación. ");

       }
           
    
          

        }catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
       
     
     
     }
         
          public void cargarItem(int id)
    {
        ControllerItemList controller=new ControllerItemList();
        
        ArrayList lista=controller.listarItem(id);
        
        cb_item.removeAllItems();
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_item.addItem(lista.get(i));
            }
        }
    }
       
          
        public void buscarProveedores() throws SQLException
    {
        
        conexion=new ConexionBD();
        ResultSet obj=conexion.executeQuery("SELECT prove_razon_social FROM proveedores.proveedor WHERE prove_razon_social ilike '%"+txt_proveedor.getText().toUpperCase()+"%' ORDER BY prove_razon_social ASC");
        
        while(obj.next())
        {
            cb_proveedor.addItem(obj.getObject("prove_razon_social"));
        }
      
        conexion.desconectar();
        
    }      
        
        
        public void filtro() {
        int columnaABuscar = 0;
        if (cb_filtro.getSelectedItem().toString() == "ID") {
            columnaABuscar = 0;
        }
        if (cb_filtro.getSelectedItem() == "Referencia") {
            columnaABuscar = 3;
        }
        if (cb_filtro.getSelectedItem() == "Descripción") {
            columnaABuscar = 4;
        }
       
        
        trsFiltro.setRowFilter(RowFilter.regexFilter(txt_filtro.getText(), columnaABuscar));
}

}
