/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sys.utd.Presentacion;

import com.sys.utd.ConexionBD.ConexionBD;
import com.sys.utd.ConexionBD.ConexionBDM;
import com.sys.utd.Daos.Dao_Det_Pedido;
import com.sys.utd.Daos.Dao_Pedidos;
import com.sys.utd.Entidades.Entidad_Det_Pedido;
import com.sys.utd.Entidades.Entidad_Pedidos;
import com.sys.utd.Entidades.ItemCentroCostos;
import com.sys.utd.Reportes.ReportePedido;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Jonathan
 */
public class JIFPedidos extends javax.swing.JInternalFrame {

   
    private ConexionBD conexion;
    private ConexionBDM conexionM;
    private DefaultTableModel modelo;
    private DefaultTableModel modeloLista;
    private Entidad_Pedidos pedido;
    private Entidad_Det_Pedido detPedido;
    private Dao_Pedidos daoPedido;
    private Dao_Det_Pedido daoDetPed;
    private int idus=MDIPrincipal.getvSeccion();
    private int id_tabla;
    private int idpedido=0;
    private ReportePedido reportePedido;
    private int iditemccostos;
    
    
    
    public JIFPedidos() {
        try {
            initComponents();
            
            conexion=new ConexionBD();
            Color c1=new Color(66,111,166);
            Color c2=new Color(102,174,118);
            JPColor miColor=new JPColor(c1,c2);
            miColor.setSize(this.getSize());
            panel_enca.add(miColor);
            
            ResultSet obj=conexion.executeQuery("SELECT nombre_centro_costos FROM utdvvcc.centrocostos WHERE estado=true ORDER BY nombre_centro_costos ASC");//Consulta para traer el nombre de centro de costos
            
            while(obj.next())
            {
                cb_ccostos.addItem(obj.getObject("nombre_centro_costos"));//Llena JCombobox con el nombre del centro de costos
            }
            
            ResultSet obj1=conexion.executeQuery("SELECT nombre_dirmant FROM utdvvcc.direcmant ORDER BY nombre_dirmant ASC");//Consulta para traer el nombre de centro de costos
            
            while(obj1.next())
            {
                cb_director.addItem(obj1.getObject("nombre_dirmant"));//Llena JCombobox con el nombre del centro de costos
            }
            
            
            
            ResultSet obj2=conexion.executeQuery("SELECT MAX(id_pedido)+1 AS idpedido FROM listadopedidos.pedido");
            
            while(obj2.next())
            {
                txt_id.setText(String.valueOf(obj2.getInt("idpedido")));//Le asigna el consecutivo siguiente de orden compra al textfield
            }
            
            conexion.desconectar();
            
            modelo=new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("IT");
            modelo.addColumn("Referencia");
            modelo.addColumn("Descripción");
            modelo.addColumn("UM");
            modelo.addColumn("Cantidad");
            modelo.addColumn("Observaciones");
            
            modeloLista=new DefaultTableModel();
            modeloLista.addColumn("Referencia");
            modeloLista.addColumn("Descripción");
            modeloLista.addColumn("UM");
        } catch (SQLException ex) {
            Logger.getLogger(JIFPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Detalle = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_item = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_des = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ref = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_um = new javax.swing.JTextField();
        txt_can = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_catalogo = new javax.swing.JButton();
        JD_Lista_Insumos = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_refeb = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_desb = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_sel = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_insumos = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        JD_Mod = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txt_item1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_des1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_ref1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_um1 = new javax.swing.JTextField();
        txt_can1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_area1 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btn_agregar1 = new javax.swing.JButton();
        btn_catalogo1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_ccostos = new javax.swing.JComboBox();
        cb_item = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cb_director = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_detalle = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_terminar = new javax.swing.JButton();
        panel_enca = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Pedido"));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Item *");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Descripción *");

        txt_des.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Referencia *");

        txt_ref.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Cantidad *");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("UM *");

        txt_um.setEditable(false);

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane3.setViewportView(txt_area);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Observación");

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Campos Obligatorios *");

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/catalogo.png"))); // NOI18N
        btn_catalogo.setToolTipText("Catálogo de Insumos");
        btn_catalogo.setBorderPainted(false);
        btn_catalogo.setContentAreaFilled(false);
        btn_catalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_catalogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregar)
                .addGap(19, 19, 19))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_item, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txt_um)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_ref, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_des, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_can, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(txt_um, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_can, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_catalogo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(btn_agregar)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout JD_DetalleLayout = new javax.swing.GroupLayout(JD_Detalle.getContentPane());
        JD_Detalle.getContentPane().setLayout(JD_DetalleLayout);
        JD_DetalleLayout.setHorizontalGroup(
            JD_DetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_DetalleLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JD_DetalleLayout.setVerticalGroup(
            JD_DetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JD_Lista_Insumos.setTitle("Buscar Insumo");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        jLabel11.setText("Referencia");

        jLabel12.setText("Descripción");

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/buscar.png"))); // NOI18N
        btn_buscar.setToolTipText("Buscar Insumo");
        btn_buscar.setBorderPainted(false);
        btn_buscar.setContentAreaFilled(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txt_refeb, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txt_desb, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscar)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txt_desb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txt_refeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Insumos"));

        btn_sel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/sel.png"))); // NOI18N
        btn_sel.setToolTipText("Seleccionar Fila");
        btn_sel.setBorderPainted(false);
        btn_sel.setContentAreaFilled(false);
        btn_sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selActionPerformed(evt);
            }
        });

        tb_insumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tb_insumos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btn_sel)
                .addGap(0, 307, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout JD_Lista_InsumosLayout = new javax.swing.GroupLayout(JD_Lista_Insumos.getContentPane());
        JD_Lista_Insumos.getContentPane().setLayout(JD_Lista_InsumosLayout);
        JD_Lista_InsumosLayout.setHorizontalGroup(
            JD_Lista_InsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_Lista_InsumosLayout.setVerticalGroup(
            JD_Lista_InsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_Lista_InsumosLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Pedido"));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Item *");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Descripción *");

        txt_des1.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Referencia *");

        txt_ref1.setEditable(false);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Cantidad *");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("UM *");

        txt_um1.setEditable(false);

        txt_area1.setColumns(20);
        txt_area1.setRows(5);
        jScrollPane5.setViewportView(txt_area1);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Observación");

        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Campos Obligatorios *");

        btn_agregar1.setText("Agregar");
        btn_agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar1ActionPerformed(evt);
            }
        });

        btn_catalogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/catalogo.png"))); // NOI18N
        btn_catalogo1.setToolTipText("Catálogo de Insumos");
        btn_catalogo1.setBorderPainted(false);
        btn_catalogo1.setContentAreaFilled(false);
        btn_catalogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_catalogo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregar1)
                .addGap(19, 19, 19))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_item1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(txt_um1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txt_ref1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_des1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txt_can1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_catalogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txt_des1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txt_ref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(txt_um1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_can1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btn_catalogo1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(btn_agregar1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout JD_ModLayout = new javax.swing.GroupLayout(JD_Mod.getContentPane());
        JD_Mod.getContentPane().setLayout(JD_ModLayout);
        JD_ModLayout.setHorizontalGroup(
            JD_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ModLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JD_ModLayout.setVerticalGroup(
            JD_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Requisición de Pedidos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        jLabel1.setText("ID Pedido *");

        txt_id.setEditable(false);

        jLabel2.setText("Centro Costos *");

        cb_ccostos.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_ccostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ccostosActionPerformed(evt);
            }
        });

        cb_item.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_area2.setColumns(20);
        txt_area2.setRows(5);
        jScrollPane1.setViewportView(txt_area2);

        jLabel3.setText("Observaciones");

        jLabel13.setText("Director *");

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Campos Obligatorios *");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_director, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(cb_ccostos, 0, 314, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_item, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_ccostos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(cb_director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel16))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Pedido"));

        tb_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tb_detalle);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/add.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/mod_detalle.png"))); // NOI18N
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/delete.png"))); // NOI18N
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_mod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_terminar.setText("Terminar");
        btn_terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terminarActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(204, 0, 0));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 51));
        jLabel14.setText("PEDIDOS");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sys/utd/Recursos/pedido.png"))); // NOI18N

        javax.swing.GroupLayout panel_encaLayout = new javax.swing.GroupLayout(panel_enca);
        panel_enca.setLayout(panel_encaLayout);
        panel_encaLayout.setHorizontalGroup(
            panel_encaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_encaLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_encaLayout.setVerticalGroup(
            panel_encaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_encaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(30, 30, 30))
            .addGroup(panel_encaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_terminar)
                .addContainerGap())
            .addComponent(panel_enca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_enca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_terminar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_ccostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ccostosActionPerformed
          try
        {
            conexion=new ConexionBD();
            
            int id_ccostos=0;

            if(cb_ccostos.getSelectedItem()!=null)
            {
                String centro=cb_ccostos.getSelectedItem().toString();
                ResultSet obj=conexion.executeQuery("SELECT id_centrocostos FROM utdvvcc.centrocostos WHERE nombre_centro_costos='"+centro+"'");

                while(obj.next())
                {
                    id_ccostos=obj.getInt("id_centrocostos");
                }
                cb_item.removeAllItems();
            }
            cargarItem(id_ccostos);
            conexion.desconectar();
            

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cb_ccostosActionPerformed

    private void btn_catalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_catalogoActionPerformed
       JD_Lista_Insumos.pack();      
       JD_Lista_Insumos.setVisible(true);
       JD_Lista_Insumos.setResizable(false);
    }//GEN-LAST:event_btn_catalogoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JD_Detalle.pack();
       JD_Detalle.setLocationRelativeTo(null);
       JD_Detalle.setVisible(true);
       JD_Detalle.setResizable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try {
            LimpiarTabla2();
            buscarInsumo();
        } catch (SQLException ex) {
            Logger.getLogger(JIFPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selActionPerformed
         
         String ref,des,um;
     
        if(tb_insumos.isRowSelected(tb_insumos.getSelectedRow()))
            {
                ref =(String) tb_insumos.getValueAt(tb_insumos.getSelectedRow(), 0);    
                des=(String) tb_insumos.getValueAt(tb_insumos.getSelectedRow(), 1);
                um=(String) tb_insumos.getValueAt(tb_insumos.getSelectedRow(), 2);
                
                
                txt_ref.setText(ref);
                txt_des.setText(des);
                txt_um.setText(um);
                
                
                txt_ref1.setText(ref);
                txt_des1.setText(des);
                txt_um1.setText(um);
                
                JD_Lista_Insumos.dispose();
                
                txt_refeb.setText("");
                txt_desb.setText("");
                 
     
            }else
            {
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla!", "Alerta!", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btn_selActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
       try
       {
        
        
        int  iddir=0;
        String ref, Des, um, obse;
        float can, item=0;
        conexion=new ConexionBD();
        pedido=new Entidad_Pedidos();
        detPedido=new Entidad_Det_Pedido();
        daoPedido=new Dao_Pedidos();
        daoDetPed=new Dao_Det_Pedido();
       
        
        
        ResultSet obj0=conexion.executeQuery("SELECT id_pedido FROM listadopedidos.pedido WHERE id_pedido="+txt_id.getText()+"");

            if(obj0.next()==false)
            {
        
          ItemCentroCostos itemCentro= (ItemCentroCostos) cb_item.getSelectedItem();
          iditemccostos=itemCentro.getIditem();
            
            if(cb_director.getSelectedItem()!=null)
            {
                String nomDir=cb_director.getSelectedItem().toString();
                ResultSet obj2=conexion.executeQuery("SELECT iddirecmant FROM utdvvcc.direcmant WHERE nombre_dirmant='"+nomDir+"'");
                           
                while(obj2.next())
                {
                    iddir=obj2.getInt("iddirecmant");
                }
            
            }
            
            pedido.setIditem(iditemccostos);
            pedido.setIddir(iddir);
            pedido.setIdus(idus);
            pedido.setFecha(new Date());
            pedido.setObse(txt_area2.getText());
            
            daoPedido.guardar(pedido);
            idpedido=Dao_Pedidos.getId_pedido();
            
            txt_id.setText(String.valueOf(idpedido)); //ID de la transacción
            
            item=Float.parseFloat(txt_item.getText());
            ref=txt_ref.getText();
            Des=txt_des.getText();
            um=txt_um.getText();
            obse=txt_area.getText();
            can=Float.parseFloat(txt_can.getText());
            
            
            detPedido.setIdpedido(idpedido);    
            detPedido.setItem(item);
            detPedido.setDescripcion(Des);
            detPedido.setReferencia(ref);
            detPedido.setUm(um);
            detPedido.setObservacion(obse);
            detPedido.setCantidad(can);
            detPedido.setCan_parcial(can);
            
            
            daoDetPed.guardar(detPedido);
            LimpiarTabla();
            detalleTabla();
            limpiar();
            
            
       }else
            {
            item=Float.parseFloat(txt_item.getText());
            ref=txt_ref.getText();
            Des=txt_des.getText();
            um=txt_um.getText();
            obse=txt_area.getText();
            can=Float.parseFloat(txt_can.getText());
            
            
            detPedido.setIdpedido(idpedido);
            detPedido.setItem(item);
            detPedido.setDescripcion(Des);
            detPedido.setReferencia(ref);
            detPedido.setUm(um);
            detPedido.setObservacion(obse);
            detPedido.setCantidad(can);
            detPedido.setCan_parcial(can);
            
            
            daoDetPed.guardar(detPedido);
            LimpiarTabla();
            detalleTabla();
            limpiar();
            
            conexion.executeUpdateQuery("UPDATE listadopedidos.pedido SET observaciones='"+txt_area2.getText()+"' WHERE id_pedido="+txt_id.getText()+"");
            conexion.desconectar();
            }
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
       }
           
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
         int opc=JOptionPane.showConfirmDialog(null,"Desea eliminar una Linea?", "Aviso!", JOptionPane.YES_NO_OPTION); 
          
        if(opc==JOptionPane.YES_OPTION)
        {
             eliminarRegistroTabla();
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        
        String ref,des,um,obs;
        float cantidad, item;
        
        
         if(tb_detalle.isRowSelected(tb_detalle.getSelectedRow()))
            {
               id_tabla = (Integer) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 0);    
               item=(float) tb_detalle.getValueAt(tb_detalle.getSelectedRow(),1);
               ref=(String) tb_detalle.getValueAt(tb_detalle.getSelectedRow(),2);
               des=(String) tb_detalle.getValueAt(tb_detalle.getSelectedRow(),3);
               um=(String) tb_detalle.getValueAt(tb_detalle.getSelectedRow(),4);
               cantidad= (float) tb_detalle.getValueAt(tb_detalle.getSelectedRow(),5);
               obs= (String) tb_detalle.getValueAt(tb_detalle.getSelectedRow(),6);

               
               
               
               txt_item1.setText(String.valueOf(item));
               txt_ref1.setText(ref);
               txt_des1.setText(des);
               txt_um1.setText(um);
               txt_can1.setText(String.valueOf(cantidad));
               txt_area1.setText(obs);
               
               
               
               
               JD_Mod.pack();
               JD_Mod.setLocationRelativeTo(null);
               JD_Mod.setVisible(true);
               JD_Mod.setResizable(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla!", "Alerta!", JOptionPane.WARNING_MESSAGE);
            }
        
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar1ActionPerformed
        float item;
        String ref,des,um,obs;
        float cantidad;
        
        detPedido=new Entidad_Det_Pedido();
        daoDetPed=new Dao_Det_Pedido();
        conexion=new ConexionBD();
        item=Float.parseFloat(txt_item1.getText());
        ref=txt_ref1.getText();
        des=txt_des1.getText();
        um=txt_um1.getText();
        obs=txt_area1.getText();
        
        cantidad=Float.parseFloat(txt_can1.getText());
        
        detPedido.setIdpedido(id_tabla);
        detPedido.setItem(item);
        detPedido.setReferencia(ref);
        detPedido.setDescripcion(des);
        detPedido.setUm(um);
        detPedido.setObservacion(obs);
        detPedido.setCantidad(cantidad);
        detPedido.setCan_parcial(cantidad);
        
        try {
            daoDetPed.update(detPedido);
            LimpiarTabla();
            detalleTabla();
            limpiar();
            conexion.executeUpdateQuery("UPDATE listadopedidos.pedido SET observaciones='"+txt_area2.getText()+"' WHERE id_pedido="+txt_id.getText()+"");
            conexion.desconectar();
            
            
            JD_Mod.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_agregar1ActionPerformed

    private void btn_catalogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_catalogo1ActionPerformed
       JD_Lista_Insumos.pack();      
       JD_Lista_Insumos.setVisible(true);
       JD_Lista_Insumos.setResizable(false);
    }//GEN-LAST:event_btn_catalogo1ActionPerformed

    private void btn_terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terminarActionPerformed
         int id;
        
            conexion=new ConexionBD();
            
            
            reportePedido=new ReportePedido();
        
            id=Integer.parseInt(txt_id.getText());
        
            reportePedido.ejecutarReporte(id);
            
             conexion.executeUpdateQuery("UPDATE listadopedidos.pedido SET observaciones='"+txt_area2.getText()+"' WHERE id_pedido="+txt_id.getText()+"");
             conexion.desconectar();
            
            this.dispose();
            

        
        
    }//GEN-LAST:event_btn_terminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_Detalle;
    private javax.swing.JDialog JD_Lista_Insumos;
    private javax.swing.JDialog JD_Mod;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_agregar1;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_catalogo;
    private javax.swing.JButton btn_catalogo1;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_sel;
    private javax.swing.JButton btn_terminar;
    private javax.swing.JComboBox cb_ccostos;
    private javax.swing.JComboBox cb_director;
    private javax.swing.JComboBox cb_item;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel panel_enca;
    private javax.swing.JTable tb_detalle;
    private javax.swing.JTable tb_insumos;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextArea txt_area1;
    private javax.swing.JTextArea txt_area2;
    private javax.swing.JTextField txt_can;
    private javax.swing.JTextField txt_can1;
    private javax.swing.JTextField txt_des;
    private javax.swing.JTextField txt_des1;
    private javax.swing.JTextField txt_desb;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_item;
    private javax.swing.JTextField txt_item1;
    private javax.swing.JTextField txt_ref;
    private javax.swing.JTextField txt_ref1;
    private javax.swing.JTextField txt_refeb;
    private javax.swing.JTextField txt_um;
    private javax.swing.JTextField txt_um1;
    // End of variables declaration//GEN-END:variables

    public void buscarInsumo() throws SQLException
    {
        conexionM=new ConexionBDM();
       
        ResultSet obj=conexionM.executeQuery("SELECT CONVERT(CAST(CONVERT(a.referencia USING latin1) AS BINARY) USING utf8),CONVERT(CAST(CONVERT(a.descripcion USING latin1) AS BINARY) USING utf8), um.nombre FROM articulos a JOIN embalajes um ON um.codembalaje=a.codembalaje WHERE a.referencia LIKE '%"+txt_refeb.getText()+"%' AND a.descripcion LIKE '%"+txt_desb.getText()+"%'");
        
        
        while (obj.next()) 
        {
        
        Object [] datos = new Object[3];
        
     
        for (int i=0;i<3;i++)
        {
            datos[i] =obj.getObject(i+1);
        }

         modeloLista.addRow(datos);
       
        }
           tb_insumos.setModel(modeloLista);
           
        TableColumnModel columnModel =tb_insumos.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(2);
        
           setCellRender(tb_insumos);
           conexionM.desconectar();
    
    }
    
        public void LimpiarTabla()
    {
  
        for(int i=modelo.getRowCount()-1;i>=0;i--)
        {
            modelo.removeRow(i);
            
        }
    }
        
            public void LimpiarTabla2()
            {
  
                    for(int i=modeloLista.getRowCount()-1;i>=0;i--)
                    {
                        modeloLista.removeRow(i);
            
                    }
            }

        public void setCellRender(JTable table) {
            Enumeration<TableColumn> en = table.getColumnModel().getColumns();
                    while (en.hasMoreElements()) {
                        TableColumn tc = en.nextElement();
                        tc.setCellRenderer(new CellRenderer());
        }
    }
        
        
    public void detalleTabla()
    {
        try
        {
            conexion=new ConexionBD();
            

            
           ResultSet obj=conexion.executeQuery("SELECT d.id_dt,d.item,d.referencia,d.descripcion,d.um,d.cantidad,d.observacion FROM listadopedidos.detalle_pedido d  WHERE d.id_pedido="+txt_id.getText()+" ORDER BY d.item");
            
            
            while (obj.next()) 
        {
        
        Object [] datos = new Object[7];
        
     
        for (int i=0;i<7;i++)
        {
            datos[i] =obj.getObject(i+1);
        }

         modelo.addRow(datos);
       
        }
           tb_detalle.setModel(modelo);
            
       
           
        TableColumnModel columnModel =tb_detalle.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(5);
        columnModel.getColumn(1).setPreferredWidth(5);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(100);
        columnModel.getColumn(4).setPreferredWidth(5);
        columnModel.getColumn(5).setPreferredWidth(10);
        columnModel.getColumn(6).setPreferredWidth(50);
     
           
           
     
           setCellRender(tb_detalle);
           conexion.desconectar();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
     public void eliminarRegistroTabla()
    {
         conexion=new ConexionBD();
        
        //Verifica que la fila de la tabla esta seleccionada
        if(tb_detalle.isRowSelected(tb_detalle.getSelectedRow()))
        {
           int row = tb_detalle.getSelectedRow();

        for(int i = 0; i < modelo.getRowCount(); i++)
        {
           conexion.executeUpdateQuery("DELETE FROM listadopedidos.detalle_pedido WHERE id_dt="+modelo.getValueAt(row,0)+" ");

        }
         int numRows = tb_detalle.getSelectedRows().length;
         
         for(int i = 0; i < numRows ; i++ )
         {
            modelo.removeRow(row);
         } 
          
        }         
 
     else
     {
      JOptionPane.showMessageDialog(this, "Debe seleccionar un registro de la tabla para eliminarlo!."
         ,"Aviso", JOptionPane.WARNING_MESSAGE);
     }
          conexion.desconectar(); 
          LimpiarTabla();
          detalleTabla();  
    }
     
     public void limpiar()
     {
         txt_item.setText("1");
         txt_item1.setText("1");
         txt_ref.setText("");
         txt_ref1.setText("");
         txt_des.setText("");
         txt_des1.setText("");
         txt_um.setText("");
         txt_um1.setText("");
         txt_can.setText("1");
         txt_can1.setText("1");
         txt_area.setText("");
         txt_area1.setText("");
         
     }
     
      public void cargarItem(int id)
    {
        ControllerItemList controller=new ControllerItemList();
        
        ArrayList lista=controller.listarItem(id);
        
        cb_item.removeAllItems();
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_item.addItem(lista.get(i));
            }
        }
    }

}
